version: "3.9"

services:
  web:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./DockerfileServer
    environment:
      - PORT=3000
      - DB_HOST=mongodb
    ports:
      - "3000:3000"
    command: ["node", "dist/src/app.js"]

  ui:
    depends_on:
      - web
    build:
      context: .
      dockerfile: ./DockerfileUI
    ports:
      - "8080:80"
    command: ["npx", "webpack", "serve"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: