version: "3.9"

services:
  web:
    depends_on:
      - mongodb
    build: .
    environment:
      - PORT=3000
      - DB_HOST=mongodb
    ports:
      - "3000:3000"
    command: ["node", "packages/server/dist/src/app.js"]

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: