name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm run bootstrap
    - run: npm run build    
  check:
    name: Linter & Prettier
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run eslint
    - run: npm run prettier
  unit-test-server:
    name: Server Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm run bootstrap:server 
    - run: npm run unit-test:server
  unit-test-ui:
    name: UI Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm run bootstrap:ui 
    - run: npm run unit-test:ui
  component-test-server:
    name: Server Component Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm run bootstrap:server 
    - run: npm run component-test:server
  component-test-ui:
    name: UI Component Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cypress-io/github-action@v4.2.2
      with:
        working-directory: ./packages/ui
        component: true
  e2e-test:
    name: E2E Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.2.0
    - run: npm run bootstrap:e2e-test
    - run: npm run api-test
    - run: npm run ui-test
