name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build
  check:
    name: Linter & Prettier
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run eslint
    - run: npm run prettier
  unit-test:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run unit-test:server
  component-test:
    name: Component Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run component-test:server
  e2e-api-test:
    name: E2E API Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: isbang/compose-action@v1.2.0
    - uses: cypress-io/github-action@v4.2.0
      with:
        project: ./test/e2e
