name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build
  check:
    name: Linter & Prettier
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run eslint
    - run: npm run prettier
  test:
    name: Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run test:server